services:
  # Backend API Service
  - type: web
    name: phygital-backend
    env: docker
    dockerfilePath: ./phygital-facility-manager/backend/Dockerfile
    dockerContext: ./phygital-facility-manager/backend
    region: oregon
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_RnWCiGa64cZz@ep-twilight-salad-a8s70q3n.eastus2.azure.neon.tech/gopalan_atlantis?sslmode=require
      - key: FIREFLY_BASE_URL
        value: https://firefly-iii-production.onrender.com
      - key: FIREFLY_API_TOKEN
        sync: false
      - key: OPENAI_API_URL
        value: https://api.openai.com/v1
      - key: OPENAI_ORG_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_ASSISTANT_ID
        sync: false
      - key: OPENAI_VECTOR_STORE_ID
        sync: false
      - key: CLICKUP_CLIENT_ID
        sync: false
      - key: CLICKUP_CLIENT_SECRET
        sync: false
      - key: CLICKUP_API_TOKEN
        sync: false
      - key: CLICKUP_TEAM_ID
        sync: false
      - key: CLICKUP_SPACE_ID
        sync: false
      - key: CLICKUP_LIST_ID
        sync: false
      - key: CLICKUP_FOLDER_ID
        sync: false
      - key: OCR_SPACE_API_KEY
        sync: false

  # Frontend Static Site Service
  - type: static
    name: phygital-frontend
    buildCommand: cd phygital-facility-manager/frontend && npm ci && npm run build
    staticPublishPath: ./phygital-facility-manager/frontend/dist
    region: oregon
    plan: starter
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    envVars:
      - key: VITE_API_URL
        value: https://phygital-backend.onrender.com
