import { precacheAndRoute } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { NetworkFirst } from 'workbox-strategies'

// Precache all of the assets generated by your build process.
self.__WB_MANIFEST && precacheAndRoute(self.__WB_MANIFEST)

// Handle offline requests for documents
registerRoute(
  ({ request }) => request.destination === 'document',
  new NetworkFirst()
)

// Handle offline requests for images
registerRoute(
  ({ request }) => request.destination === 'image',
  new NetworkFirst()
)
